// 设置mutations方法名,方便修改
export const SETLOADSHOW = 'SETLOADSHOW'
export const GETSINGERID = 'GETSINGERID'
export const GETMUSICLIST = 'GETMUSICLIST'
export const SET_PLAYING = 'SET_PLAYING'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'  
export const SET_RANDOM_INDEX = 'SET_RANDOM_INDEX'
export const SET_SONG = 'SET_SONG'
export const SET_LYRIC = 'SET_LYRIC'  
export const GETLYRICLINE = 'GETLYRICLINE'